name: Node CI

on:
  push:
    branches:
      - main # or whatever branch you want to trigger this workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js environment with npm registry URL
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      # Clean installation
      - name: Clean and Install
        run: |
          npm ci

      # Package the project
      - name: Package
        run: npm run package

      # Copy package.json to dist folder
      - run: cp package.json ./dist

      # Publish to npm registry
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd dist
          npm publish
